import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_csv('result/predicted-personality.csv')

size_s = 9.5
size_m = 12
size_l = 16

plt.rc('font', size=size_m)
plt.rc('axes', titlesize=size_l)
plt.rc('axes', labelsize=size_m)
plt.rc('xtick', labelsize=size_s)
plt.rc('ytick', labelsize=size_m)
plt.rc('legend', fontsize=size_s)
plt.rc('figure', titlesize=size_l)

# AGREEABLENESS ===============================================================

dataA = pd.read_csv('result/predicted-personality.csv')
dataA.drop(dataA.loc[dataA['Predicted'] != 'Agreeableness'].index, inplace=True)

chartAS = dataA.groupby(['Predicted'])[['Positive','Negative']].mean()
chartAS.plot.bar()
plt.xticks(rotation=0)
plt.yticks(np.arange(0, 14, 2))
plt.title('Agreeableness: Sentiment')
plt.xlabel('Big Five Personality') 
plt.ylabel('Rata-rata Nilai') 
plt.tight_layout()
plt.savefig('result/sentiment-agreeableness.png')

chartAE = dataA.groupby(['Predicted'])[['Anger','Anticipation','Disgust','Fear','Joy','Sadness','Surprise','Trust']].mean()
chartAE.plot.bar()
plt.xticks(rotation=0)
plt.yticks(np.arange(0, 11, 1))
plt.title('Agreeableness: Emotion')
plt.xlabel('Big Five Personality') 
plt.ylabel('Rata-rata Nilai') 
plt.legend(ncol=2)
plt.tight_layout()
plt.savefig('result/emotion-agreeableness.png')

chartAC = dataA.groupby(['Predicted'])[['Following', 'Followers', 'Retweet', 'Favorite']].mean()
chartAC.plot.bar()
plt.xticks(rotation=0)
plt.yticks(np.arange(0, 800, 100))
plt.title('Agreeableness: Social')
plt.xlabel('Big Five Personality') 
plt.ylabel('Rata-rata Nilai')
plt.legend(ncol=2) 
plt.tight_layout()
plt.savefig('result/social-agreeableness.png')

print("\n- visualizing to 'result/agreeableness.png' complete.")

# CONSCIENTIOUSNESS ===============================================================

dataC = pd.read_csv('result/predicted-personality.csv')
dataC.drop(dataC.loc[dataC['Predicted'] != 'Conscientiousness'].index, inplace=True)

chartCS = dataC.groupby(['Predicted'])[['Positive','Negative']].mean()
chartCS.plot.bar()
plt.xticks(rotation=0)
plt.yticks(np.arange(0, 14, 2))
plt.title('Conscientiousness: Sentiment')
plt.xlabel('Big Five Personality') 
plt.ylabel('Rata-rata Nilai') 
plt.tight_layout()
plt.savefig('result/sentiment-conscientiousness.png')

chartCE = dataC.groupby(['Predicted'])[['Anger','Anticipation','Disgust','Fear','Joy','Sadness','Surprise','Trust']].mean()
chartCE.plot.bar()
plt.xticks(rotation=0)
plt.yticks(np.arange(0, 11, 1))
plt.title('Conscientiousness: Emotion')
plt.xlabel('Big Five Personality') 
plt.ylabel('Rata-rata Nilai') 
plt.legend(ncol=2) 
plt.tight_layout()
plt.savefig('result/emotion-conscientiousness.png')

chartCC = dataC.groupby(['Predicted'])[['Following', 'Followers', 'Retweet', 'Favorite']].mean()
chartCC.plot.bar()
plt.xticks(rotation=0)
plt.yticks(np.arange(0, 1400, 200))
plt.title('Conscientiousness: Social')
plt.xlabel('Big Five Personality') 
plt.ylabel('Rata-rata Nilai') 
plt.legend(ncol=2) 
plt.tight_layout()
plt.savefig('result/social-conscientiousness.png')

print("\n- visualizing to 'result/conscientiousness.png' complete.")

# EXTRAVERSION ===============================================================

dataE = pd.read_csv('result/predicted-personality.csv')
dataE.drop(dataE.loc[dataE['Predicted'] != 'Extraversion'].index, inplace=True)

chartES = dataE.groupby(['Predicted'])[['Positive','Negative']].mean()
chartES.plot.bar()
plt.xticks(rotation=0)
plt.yticks(np.arange(0, 14, 2))
plt.title('Extraversion: Sentiment')
plt.xlabel('Big Five Personality') 
plt.ylabel('Rata-rata Nilai') 
plt.tight_layout()
plt.savefig('result/sentiment-extraversion.png')

chartEE = dataE.groupby(['Predicted'])[['Anger','Anticipation','Disgust','Fear','Joy','Sadness','Surprise','Trust']].mean()
chartEE.plot.bar()
plt.xticks(rotation=0)
plt.yticks(np.arange(0, 11, 1))
plt.title('Extraversion: Emotion')
plt.xlabel('Big Five Personality') 
plt.ylabel('Rata-rata Nilai') 
plt.legend(ncol=2)
plt.tight_layout()
plt.savefig('result/emotion-extraversion.png')

chartEC = dataE.groupby(['Predicted'])[['Following', 'Followers', 'Retweet', 'Favorite']].mean()
chartEC.plot.bar()
plt.xticks(rotation=0)
plt.yticks(np.arange(0, 1800, 200))
plt.title('Extraversion: Social')
plt.xlabel('Big Five Personality') 
plt.ylabel('Rata-rata Nilai')
plt.legend(ncol=2) 
plt.tight_layout()
plt.savefig('result/social-extraversion.png')

print("\n- visualizing to 'result/extraversion.png' complete.")

# NEUROTICISM ===============================================================

dataN = pd.read_csv('result/predicted-personality.csv')
dataN.drop(dataN.loc[dataN['Predicted'] != 'Neuroticism'].index, inplace=True)

chartNS = dataN.groupby(['Predicted'])[['Positive','Negative']].mean()
chartNS.plot.bar()
plt.xticks(rotation=0)
plt.yticks(np.arange(0, 14, 2))
plt.title('Neuroticism: Sentiment')
plt.xlabel('Big Five Personality') 
plt.ylabel('Rata-rata Nilai') 
plt.tight_layout()
plt.savefig('result/sentiment-neuroticism.png')

chartNE = dataN.groupby(['Predicted'])[['Anger','Anticipation','Disgust','Fear','Joy','Sadness','Surprise','Trust']].mean()
chartNE.plot.bar()
plt.xticks(rotation=0)
plt.yticks(np.arange(0, 11, 1))
plt.title('Neuroticism: Emotion')
plt.xlabel('Big Five Personality') 
plt.ylabel('Rata-rata Nilai') 
plt.legend(ncol=2)
plt.tight_layout()
plt.savefig('result/emotion-neuroticism.png')

chartNC = dataN.groupby(['Predicted'])[['Following', 'Followers', 'Retweet', 'Favorite']].mean()
chartNC.plot.bar()
plt.xticks(rotation=0)
plt.yticks(np.arange(0, 450, 50))
plt.title('Neuroticism: Social')
plt.xlabel('Big Five Personality') 
plt.ylabel('Rata-rata Nilai')
plt.legend(ncol=2) 
plt.tight_layout()
plt.savefig('result/social-neuroticism.png')

print("\n- visualizing to 'result/neuroticism.png' complete.")

# OPENNESS ===============================================================

dataO = pd.read_csv('result/predicted-personality.csv')
dataO.drop(dataO.loc[dataO['Predicted'] != 'Openness'].index, inplace=True)

chartOS = dataO.groupby(['Predicted'])[['Positive','Negative']].mean()
chartOS.plot.bar()
plt.xticks(rotation=0)
plt.yticks(np.arange(0, 14, 2))
plt.title('Openness: Sentiment')
plt.xlabel('Big Five Personality') 
plt.ylabel('Rata-rata Nilai') 
plt.tight_layout()
plt.savefig('result/sentiment-openness.png')

chartOE = dataO.groupby(['Predicted'])[['Anger','Anticipation','Disgust','Fear','Joy','Sadness','Surprise','Trust']].mean()
chartOE.plot.bar()
plt.xticks(rotation=0)
plt.yticks(np.arange(0, 11, 1))
plt.title('Openness: Emotion')
plt.xlabel('Big Five Personality') 
plt.ylabel('Rata-rata Nilai') 
plt.legend(ncol=2)
plt.tight_layout()
plt.savefig('result/emotion-openness.png')

chartOC = dataO.groupby(['Predicted'])[['Following', 'Followers', 'Retweet', 'Favorite']].mean()
chartOC.plot.bar()
plt.xticks(rotation=0)
plt.yticks(np.arange(0, 450, 50))
plt.title('Openness: Social')
plt.xlabel('Big Five Personality') 
plt.ylabel('Rata-rata Nilai')
plt.legend(ncol=2) 
plt.tight_layout()
plt.savefig('result/social-openness.png')

print("\n- visualizing to 'result/openness.png' complete.")
plt.close('all')

# SENTIMENT =========================================================
pos = df.groupby(['Predicted'])[['Positive']].mean()
pos.plot.bar(color = 'royalblue', figsize=(6.8, 4.8))
plt.xticks(rotation=0)
plt.yticks(np.arange(0, 14, 2))
plt.xlabel('Big Five Personality') 
plt.ylabel('Total') 
plt.title('Feature Sentiment: Positive')
plt.tight_layout()
plt.savefig('result/big5-sentiment-positive.png')

neg = df.groupby(['Predicted'])[['Negative']].mean()
neg.plot.bar(color = 'firebrick', figsize=(6.8, 4.8))
plt.xticks(rotation=0)
plt.yticks(np.arange(0, 14, 2))
plt.xlabel('Big Five Personality') 
plt.ylabel('Total') 
plt.title('Feature Sentiment: Negative')
plt.tight_layout()
plt.savefig('result/big5-sentiment-negative.png')

print("\n- visualizing to 'result/big5-sentiment.png' complete.")

# EMOTION =========================================================
ang = df.groupby(['Predicted'])[['Anger']].mean()
ang.plot.bar(color = 'orangered', figsize=(6.8, 4.8))
plt.xticks(rotation=0)
plt.yticks(np.arange(0, 11, 1))
plt.xlabel('Big Five Personality') 
plt.ylabel('Total') 
plt.title('Feature Emotion: Anger')
plt.tight_layout()
plt.savefig('result/big5-emotion-anger.png')

ant = df.groupby(['Predicted'])[['Anticipation']].mean()
ant.plot.bar(color = 'gold', figsize=(6.8, 4.8))
plt.xticks(rotation=0)
plt.yticks(np.arange(0, 11, 1))
plt.xlabel('Big Five Personality') 
plt.ylabel('Total') 
plt.title('Feature Emotion: Anticipation')
plt.tight_layout()
plt.savefig('result/big5-emotion-anticipation.png')

dsg = df.groupby(['Predicted'])[['Disgust']].mean()
dsg.plot.bar(color = 'sienna', figsize=(6.8, 4.8))
plt.xticks(rotation=0)
plt.yticks(np.arange(0, 11, 1))
plt.xlabel('Big Five Personality') 
plt.ylabel('Total') 
plt.title('Feature Emotion: Disgust')
plt.tight_layout()
plt.savefig('result/big5-emotion-disgust.png')

fer = df.groupby(['Predicted'])[['Fear']].mean()
fer.plot.bar(color = 'deepskyblue', figsize=(6.8, 4.8))
plt.xticks(rotation=0)
plt.yticks(np.arange(0, 11, 1))
plt.xlabel('Big Five Personality') 
plt.ylabel('Total') 
plt.title('Feature Emotion: Fear')
plt.tight_layout()
plt.savefig('result/big5-emotion-fear.png')

joy = df.groupby(['Predicted'])[['Joy']].mean()
joy.plot.bar(color = 'hotpink', figsize=(6.8, 4.8))
plt.xticks(rotation=0)
plt.yticks(np.arange(0, 11, 1))
plt.xlabel('Big Five Personality') 
plt.ylabel('Total') 
plt.title('Feature Emotion: Joy')
plt.tight_layout()
plt.savefig('result/big5-emotion-joy.png')

sdn = df.groupby(['Predicted'])[['Sadness']].mean()
sdn.plot.bar(color = 'mediumorchid', figsize=(6.8, 4.8))
plt.xticks(rotation=0)
plt.yticks(np.arange(0, 11, 1))
plt.xlabel('Big Five Personality') 
plt.ylabel('Total') 
plt.title('Feature Emotion: Sadness')
plt.tight_layout()
plt.savefig('result/big5-emotion-sadness.png')

srp = df.groupby(['Predicted'])[['Surprise']].mean()
srp.plot.bar(color = 'sandybrown', figsize=(6.8, 4.8))
plt.xticks(rotation=0)
plt.yticks(np.arange(0, 11, 1))
plt.xlabel('Big Five Personality') 
plt.ylabel('Total') 
plt.title('Feature Emotion: Surprise')
plt.tight_layout()
plt.savefig('result/big5-emotion-surprise.png')

trs = df.groupby(['Predicted'])[['Trust']].mean()
trs.plot.bar(color = 'springgreen', figsize=(6.8, 4.8))
plt.xticks(rotation=0)
plt.yticks(np.arange(0, 11, 1))
plt.xlabel('Big Five Personality') 
plt.ylabel('Total') 
plt.title('Feature Emotion: Trust')
plt.tight_layout()
plt.savefig('result/big5-emotion-trust.png')

print("\n- visualizing to 'result/big5-emotion.png' complete.")

# SOCIAL =========================================================
flg = df.groupby(['Predicted'])[['Following']].mean()
flg.plot.bar(color = 'darkorange', figsize=(6.8, 4.8))
plt.xticks(rotation=0)
plt.yticks(np.arange(0, 800, 100))
plt.xlabel('Big Five Personality') 
plt.ylabel('Total') 
plt.title('Feature Social: Following')
plt.tight_layout()
plt.savefig('result/big5-social-following.png')

flw = df.groupby(['Predicted'])[['Followers']].mean()
flw.plot.bar(color = 'violet', figsize=(6.8, 4.8))
plt.xticks(rotation=0)
plt.yticks(np.arange(0, 1800, 200))
plt.xlabel('Big Five Personality') 
plt.ylabel('Total') 
plt.title('Feature Social: Followers')
plt.tight_layout()
plt.savefig('result/big5-social-followers.png')

rtw = df.groupby(['Predicted'])[['Retweet']].mean()
rtw.plot.bar(color = 'turquoise', figsize=(6.8, 4.8))
plt.xticks(rotation=0)
plt.yticks(np.arange(0, 200, 20))
plt.xlabel('Big Five Personality') 
plt.ylabel('Total') 
plt.title('Feature Social: Retweet')
plt.tight_layout()
plt.savefig('result/big5-social-retweet.png')

fvr = df.groupby(['Predicted'])[['Favorite']].mean()
fvr.plot.bar(color = 'tomato', figsize=(6.8, 4.8))
plt.xticks(rotation=0)
plt.yticks(np.arange(0, 700, 100))
plt.xlabel('Big Five Personality') 
plt.ylabel('Total') 
plt.title('Feature Social: Favorite')
plt.tight_layout()
plt.savefig('result/big5-social-favorite.png')

print("\n- visualizing to 'result/big5-social.png' complete.")
plt.close('all')

# ===========================================================================

# ALL FEATURE
asn = df.groupby(['Predicted'])[['Positive','Negative']].mean()
asn.plot.bar(width=0.5, figsize=(10,6))
plt.xticks(rotation=0, size=12)
plt.yticks(np.arange(0, 14, 2), size=12)
plt.title('Big Five Personality: Sentiment')
plt.xlabel(' ') 
plt.ylabel('Rata-rata Nilai') 
plt.tight_layout()
plt.savefig('result/all-sentiment.png')

aem = df.groupby(['Predicted'])[['Anger','Anticipation','Disgust','Fear','Joy','Sadness','Surprise','Trust']].mean()
aem.plot.bar(width=0.6, figsize=(14,6))
plt.xticks(rotation=0, size=12)
plt.yticks(np.arange(0, 11, 1), size=14)
plt.title('Big Five Personality: Emotion')
plt.xlabel(' ') 
plt.ylabel('Rata-rata Nilai') 
plt.legend(ncol=2)
plt.tight_layout()
plt.savefig('result/all-emotion.png')

asc = df.groupby(['Predicted'])[['Following', 'Followers', 'Retweet', 'Favorite']].mean()
asc.plot.bar(width=0.8, figsize=(10,6))
plt.xticks(rotation=0, size=12)
plt.yticks(np.arange(0, 1700, 200), size=12)
plt.title('Big Five Personality: Social')
plt.xlabel(' ') 
plt.ylabel('Rata-rata Nilai') 
plt.legend(ncol=2)
plt.tight_layout()
plt.savefig('result/all-social.png')

print("\n- visualizing to 'result/all-feature.png' complete.")

# ===========================================================================
